/* Boundary Research Institute — Archive Terminal
   Reads window.ARCHIVE_DATA (generated by build.py) and renders it as a
   classified, cross-linked, paginated CRT archive. No dependencies. */

(function () {
  "use strict";

  // ---------- elements ----------
  const out   = document.getElementById("out");
  const cmd   = document.getElementById("cmd");
  const ps1   = document.getElementById("ps1");
  const clock = document.getElementById("clock");
  const hush  = document.getElementById("hush");
  const promptLine = document.getElementById("prompt-line");
  const screen = document.getElementById("screen");
  const authPad = document.createElement("div");
  let authKeyHandler = null;
  let authKeyValue = "";
  let authPromptLabel = "auth>";

  authPad.className = "auth-pad hidden";
  authPad.innerHTML =
    '<div class="auth-pad-title">TOUCH KEYPAD // TAP TO TYPE</div>' +
    '<div class="auth-pad-grid">' +
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").map(function (ch) {
        return '<button class="auth-key" type="button" data-auth-key="' + ch + '">' + ch + "</button>";
      }).join("") +
    "</div>" +
    '<div class="auth-pad-actions">' +
      '<button class="auth-key auth-key-wide" type="button" data-auth-key="Y">Y</button>' +
      '<button class="auth-key auth-key-wide" type="button" data-auth-key="N">N</button>' +
      '<button class="auth-key auth-key-wide" type="button" data-auth-key="Backspace">BKSP</button>' +
      '<button class="auth-key auth-key-wide" type="button" data-auth-key="Escape">ESC</button>' +
      '<button class="auth-key auth-key-wide auth-key-enter" type="button" data-auth-key="Enter">ENTER</button>' +
    "</div>";
  screen.insertBefore(authPad, promptLine);

  document.addEventListener("contextmenu", function (ev) {
    ev.preventDefault();
    ev.stopPropagation();
  }, true);

  document.addEventListener("dragstart", function (ev) {
    ev.preventDefault();
    ev.stopPropagation();
  }, true);

  function authEvent(key) {
    return {
      key: key,
      preventDefault: function () {},
      stopPropagation: function () {},
    };
  }

  function focusAuthInput() {
    if (!authKeyHandler) return;
    cmd.value = "";
    authKeyValue = "";
    if (window.matchMedia("(pointer: coarse)").matches) return;
    setTimeout(function () {
      if (!authKeyHandler) return;
      try { cmd.focus({ preventScroll: true }); }
      catch (_) { cmd.focus(); }
    }, 0);
  }

  function setAuthKeyHandler(handler, label) {
    authKeyHandler = handler;
    authPromptLabel = label || "auth>";
    cmd.value = "";
    authKeyValue = "";
    if (handler) {
      const isAckPrompt = authPromptLabel === "ack>";
      authPad.classList.toggle("auth-pad-ack", authPromptLabel === "ack>");
      authPad.classList.toggle(
        "auth-pad-reconnect",
        authPromptLabel === "reconnect>" || authPromptLabel === "init>"
      );
      authPad.querySelector('.auth-pad-actions [data-auth-key="Y"]').textContent =
        isAckPrompt ? "AUTHORIZE [Y]" : "Y";
      authPad.querySelector('.auth-pad-actions [data-auth-key="N"]').textContent =
        isAckPrompt ? "TERMINATE [N]" : "N";
      ps1.textContent = authPromptLabel;
      promptLine.classList.remove("hidden");
      cmd.disabled = false;
      authPad.classList.remove("hidden");
      focusAuthInput();
      window.setTimeout(scrollBottom, 0);
    } else {
      ps1.textContent = "archive>";
      cmd.value = "";
      authPad.classList.add("hidden");
      authPad.classList.remove("auth-pad-ack", "auth-pad-reconnect");
      cmd.blur();
    }
  }

  cmd.addEventListener("input", function () {
    if (!authKeyHandler) return;
    const next = cmd.value || "";
    if (next.length < authKeyValue.length) {
      for (let i = 0; i < (authKeyValue.length - next.length); i++) authKeyHandler(authEvent("Backspace"));
    } else if (next.length > authKeyValue.length) {
      next.slice(authKeyValue.length).split("").forEach(function (ch) {
        authKeyHandler(authEvent(ch));
      });
    }
    authKeyValue = cmd.value || "";
    if (authKeyValue.length > 24) {
      cmd.value = "";
      authKeyValue = "";
    }
  });

  window.addEventListener("pointerdown", function () {
    if (authKeyHandler) focusAuthInput();
  }, true);

  authPad.addEventListener("click", function (ev) {
    const btn = ev.target.closest("[data-auth-key]");
    if (!btn || !authKeyHandler) return;
    const key = btn.getAttribute("data-auth-key");
    authKeyHandler(authEvent(key));
    focusAuthInput();
  });

  // ====================================================================
  //  In-world metadata (status stamps)
  // ====================================================================
  const CONTENT = window.ARCHIVE_CONTENT || {};
  const META = Object.assign({}, CONTENT.meta || {});
  const DEFAULT_META = { code: "??-??", status: "UNCLASSIFIED", tone: "dim" };
  const IME_SIGNAL_FRAMES = [
    "assets/ime-talk/frame-01.png",
    "assets/ime-talk/frame-02.png",
    "assets/ime-talk/frame-03.png",
  ];
  const IME_SIGNAL_FRAME_SEQUENCE = [0, 1, 2, 1, 0];
  const AUDIO_SRC = {
    boot: "assets/audio/boot-background.mp3",
    glitch: "assets/audio/glitch-sound.mp3",
  };

  const DOSSIERS = Object.assign({}, CONTENT.dossiers || {});
  const CATEGORY_NOTES = CONTENT.categoryNotes || {};

  const ARCHIVE_EVENTS = [
    {
      code: "NCE",
      level: "amber",
      title: "NONLOCAL CONVERGENCE EVENT",
      body: "All personnel are instructed to cease field movement. Maintain visual confirmation of assigned partner. Do not answer speech from unverified sources.",
      status: "HUSH LEVEL: RISING",
    },
    {
      code: "RN-03",
      level: "alert",
      title: "HOSTILE RELIGIOUS ACTIVITY DETECTED",
      body: "RN-03 affiliated movement reported near CSD sweep group. Recovery teams are to preserve subject priority and avoid doctrinal exchange.",
      status: "INTERDICTION RISK: MODERATE",
    },
    {
      code: "CSD",
      level: "amber",
      title: "SWEEP GROUP TELEMETRY GAP",
      body: "CSD unit failed to return synchronized positional data. Last confirmed signal places team inside outer Boundary band. Awaiting correction window.",
      status: "STATUS: UNRESOLVED",
    },
    {
      code: "NIS",
      level: "violet",
      title: "LINGUISTIC ANOMALY FLAG",
      body: "Recovered NIS subject has begun repeating phrases not present in prior recordings. Linguistics division requests silent-channel capture.",
      status: "TRANSLATION: PENDING",
    },
    {
      code: "BIO",
      level: "amber",
      title: "BIOLOGICAL CONTAINMENT NOTICE",
      body: "Specimen response detected in cold storage without observed locomotion. Staff experiencing reluctance to enter are to request replacement.",
      status: "AFFECTIVE INTERFERENCE: LIKELY",
    },
    {
      code: "CTA",
      level: "violet",
      title: "CHRONOLOGICAL TUNNELING ARRAY",
      body: "Temporal retention drift exceeds acceptable tolerance. Do not consult archive timestamps until checksum stabilizes.",
      status: "NONLOCALITY ERROR: ACTIVE",
    },
    {
      code: "LSTN",
      level: "alert",
      title: "UNAUTHORIZED LISTENING EVENT",
      body: "An unregistered listener pattern has been detected in the archive channel. Operators should not verbally identify themselves.",
      status: "SOURCE: UNCONFIRMED",
    },
    {
      code: "KAL",
      level: "dim",
      title: "EXTERNAL GOVERNMENT QUERY",
      body: "Kalliros liaison has requested clarification regarding maritime exclusion enforcement. Response deferred pending Directorate review.",
      status: "DIPLOMATIC HANDLING: SEALED",
    },
    {
      code: "EK-01",
      level: "dim",
      title: "CORDON PUBLIC ADVISORY",
      body: "Eirskel residents are reminded that lights observed beyond the line do not indicate safe return paths. Remain within marked streets.",
      status: "BROADCAST CLASS: CIVIL",
    },
    {
      code: "ARCH",
      level: "violet",
      title: "ARCHIVE COHERENCE WARNING",
      body: "Record count discrepancy detected. If an entry is remembered but not indexed, do not attempt manual reconstruction.",
      status: "MEMORY CHECKSUM: FAILED",
    },
  ];
  const ARCHIVE_EVENT_CODES = {
    STILLING: "NCE",
    RANESK: "RN-03",
    SWEEP: "CSD",
    NIS: "NIS",
    FAUNA: "BIO",
    ARRAY: "CTA",
    LISTENER: "LSTN",
    KALLIROS: "KAL",
    EIRSKEL: "EK-01",
    MEMORY: "ARCH",
  };
  const ARCHIVE_EVENT_KEY = "bri.archiveEventDay.v1";
  let archiveEventTimer = null;
  let archiveEventAdminOpen = false;

  // ====================================================================
  //  Section heading -> institutional label
  // ====================================================================
  const HEADING_LABELS = {
    names: "DESIGNATIONS",
    whatitis: "ASSESSMENT",
    thelawofit: "OBSERVED BEHAVIOUR",
    unnamingmemory: "EFFECT: MEMORY",
    theunnamednisandthenaarsken: "SURVIVOR CLASSIFICATION",
    listeners: "LISTENER PHENOMENON",
    thestillingevent: "PERIODIC EVENT — “THE STILLING”",
    sizeplaceclimate: "EXTENT & TERRAIN",
    howitiswatched: "MONITORING & PARTIES",
    phenomenaecology: "FLORA, FAUNA & PHENOMENA",
    temporalnonlocalitythechronologicaltunnelingarray: "TEMPORAL NONLOCALITY",
    spatialnonlocalitythecordonandtheopendoor: "SPATIAL NONLOCALITY & CORDON",
    whyitholds: "STRUCTURAL BASIS",
    whowashesuphere: "POPULATION",
    whokeepsorder: "GOVERNANCE",
    originandsuccession: "ORIGIN & SUCCESSION",
    howittakespeople: "RECRUITMENT METHOD",
    makingnaarskentheguidesbetrayal: "PRODUCTION OF SURVIVORS",
    standinginvaardencoldwar: "RELATIONS: VAARDEN",
    background: "BACKGROUND",
    relationships: "KNOWN ASSOCIATES",
  };

  // sections kept for PERSONS OF INTEREST records (everything else dropped)
  const PERSON_KEEP = { background: 1, relationships: 1 };

  function isPerson(e) { return e.group === "PERSONS OF INTEREST"; }

  function skipSectionGlobal(normTitle) {
    return /todevelop|openquestion|toreconcile/.test(normTitle);
  }

  // ====================================================================
  //  Data prep
  // ====================================================================
  const DATA = (window.ARCHIVE_DATA || []).slice();

  const SYNTHETIC = (CONTENT.synthetic || []).map(function (e) { return Object.assign({}, e); });
  const CATALOGUE = (CONTENT.catalogue || []).slice();
  CATALOGUE.forEach(function (c) {
    const key = norm(c.title);
    META[key] = { code: c.code, status: c.status || "", tone: c.tone || "" };
    DOSSIERS[key] = {
      title: c.code + " // " + c.title.toUpperCase(),
      sub: c.sub || "", fields: c.fields || [], relevance: c.relevance || "",
      media: c.media || null,
      sections: [{ label: "ASSESSMENT", md: c.body }],
    };
    SYNTHETIC.push({ title: c.title, group: c.group, raw: "", empty: false });
  });
  Array.prototype.push.apply(DATA, SYNTHETIC);

  const GROUP_OVERRIDE = Object.assign({}, CONTENT.groupOverride || {});

  const byKey = {};
  const byNumber = {};
  DATA.forEach(function (e, i) {
    e.key = norm(e.title);
    e.num = i + 1;
    e.meta = META[e.key] || DEFAULT_META;
    if (GROUP_OVERRIDE[e.key]) e.group = GROUP_OVERRIDE[e.key];
    byKey[e.key] = e;
    byNumber[e.num] = e;
  });

  function norm(s) {
    return (s || "")
      .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
      .toLowerCase().replace(/[^a-z0-9]+/g, "");
  }

  // ====================================================================
  //  Markdown -> HTML  (+ [[wikilink]] resolution, + meta stripping)
  // ====================================================================
  function escapeHtml(s) {
    return s.replace(/[&<>"]/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c];
    });
  }

  function archiveEventDay() {
    const d = new Date();
    return d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0");
  }

  function archiveEventShownToday() {
    try { return localStorage.getItem(ARCHIVE_EVENT_KEY) === archiveEventDay(); }
    catch (_) { return false; }
  }

  function markArchiveEventShown() {
    try { localStorage.setItem(ARCHIVE_EVENT_KEY, archiveEventDay()); }
    catch (_) { /* storage unavailable; session still continues */ }
  }

  function pickArchiveEvent(id) {
    if (id) {
      const key = norm(id);
      const found = ARCHIVE_EVENTS.find(function (e) {
        return norm(e.code) === key || norm(e.title) === key;
      });
      if (found) return found;
    }
    return ARCHIVE_EVENTS[Math.floor(Math.random() * ARCHIVE_EVENTS.length)];
  }

  function dismissArchiveEvent() {
    const node = document.querySelector(".archive-event");
    if (!node) return;
    node.classList.add("closing");
    setTimeout(function () { if (node.parentNode) node.parentNode.removeChild(node); }, 260);
  }

  function showArchiveEvent(id, manual) {
    if (document.querySelector(".archive-event")) return;
    const ev = pickArchiveEvent(id);
    if (!manual) markArchiveEventShown();
    const wrap = document.createElement("div");
    wrap.className = "archive-event " + (ev.level || "dim");
    wrap.innerHTML =
      '<div class="ae-card" role="dialog" aria-modal="false" aria-label="BRI advisory">' +
        '<div class="ae-kicker">BRI ADVISORY // ' + escapeHtml(ev.code) + "</div>" +
        '<div class="ae-title">' + escapeHtml(ev.title) + "</div>" +
        '<p>' + escapeHtml(ev.body) + "</p>" +
        '<div class="ae-status">' + escapeHtml(ev.status) + "</div>" +
        '<button class="ae-ack" type="button">ACKNOWLEDGE</button>' +
      "</div>";
    screen.appendChild(wrap);
    const ack = wrap.querySelector(".ae-ack");
    if (ack) ack.addEventListener("click", dismissArchiveEvent);
  }

  function closeArchiveEventAdmin() {
    const node = document.querySelector(".archive-event-admin");
    archiveEventAdminOpen = false;
    if (node && node.parentNode) node.parentNode.removeChild(node);
  }

  function showArchiveEventAdmin() {
    if (archiveEventAdminOpen) return;
    archiveEventAdminOpen = true;
    const wrap = document.createElement("div");
    wrap.className = "archive-event-admin";
    wrap.innerHTML =
      '<div class="aea-card" role="dialog" aria-modal="false" aria-label="event trigger">' +
        '<div class="aea-kicker">DIRECTORATE EVENT INJECTION</div>' +
        '<label class="aea-label">AUTH CODE</label>' +
        '<input class="aea-input" type="password" autocomplete="off" spellcheck="false">' +
        '<div class="aea-help">Ctrl+Shift+E · codes: STILLING / RANESK / SWEEP / NIS / FAUNA / ARRAY / LISTENER / KALLIROS / EIRSKEL / MEMORY</div>' +
        '<div class="aea-error" aria-live="polite"></div>' +
      "</div>";
    screen.appendChild(wrap);
    const input = wrap.querySelector(".aea-input");
    const err = wrap.querySelector(".aea-error");
    function fail() {
      if (!err) return;
      err.textContent = "AUTH CODE REJECTED";
      wrap.classList.add("denied");
      setTimeout(function () { wrap.classList.remove("denied"); }, 300);
    }
    if (input) {
      input.focus();
      input.addEventListener("keydown", function (ev) {
        if (ev.key === "Escape") {
          ev.preventDefault();
          closeArchiveEventAdmin();
          return;
        }
        if (ev.key !== "Enter") return;
        ev.preventDefault();
        const code = (input.value || "").trim().toUpperCase();
        const eventId = ARCHIVE_EVENT_CODES[code];
        if (!eventId) { fail(); return; }
        closeArchiveEventAdmin();
        showArchiveEvent(eventId, true);
      });
    }
  }

  function scheduleArchiveEvent() {
    if (archiveEventTimer || archiveEventShownToday()) return;
    const delay = (8 * 60 * 1000) + Math.floor(Math.random() * (4 * 60 * 1000));
    archiveEventTimer = setTimeout(function () {
      archiveEventTimer = null;
      if (!archiveEventShownToday()) showArchiveEvent(null, false);
    }, delay);
  }

  window.triggerArchiveEvent = function (id) {
    showArchiveEvent(id, true);
  };

  function renderWikilinks(s) {
    return s.replace(/\[\[([^\]]+)\]\]/g, function (_, body) {
      const parts = body.split("|");
      const targetTitle = parts[0].split("#")[0].trim();
      const display = (parts[1] || parts[0].split("#")[0]).trim();
      const key = norm(targetTitle);
      if (byKey[key]) {
        return '<span class="xref" data-target="' + key + '">' + escapeHtml(display) + "</span>";
      }
      return '<span class="xref-dead" title="NO RECORD ON FILE">' + escapeHtml(display) + "</span>";
    });
  }

  // remove authorial asides embedded mid-sentence
  function stripInlineMeta(s) {
    return s
      .replace(/\s*\*\([^)]*(?:draft|keep the mystery|cf\.|to develop|register|this note)[^)]*\)\*/gi, "")
      .replace(/\s*\(cf\.[^)]*\)/gi, "");
  }

  // replace in-world colloquialisms with official register
  function instituteScrub(s) {
    return s
      .replace(/\bthe Outside\b/g, "the exterior territory")
      .replace(/\bthe outside\b/g, "the exterior territory")
      .replace(/\bbeyond the line\b/gi, "beyond the cordon")
      .replace(/\bthe Down\b/g, "the subsurface shelter");
  }

  function inline(s) {
    s = stripInlineMeta(s);
    s = instituteScrub(s);
    s = escapeHtml(s);
    s = renderWikilinks(s);
    s = s.replace(/\*\*([^*]+?)\*\*/g, "<strong>$1</strong>");
    s = s.replace(/\*([^*]+?)\*/g, "<em>$1</em>");
    s = s.replace(/~~([^~]+?)~~/g, "<del>$1</del>");
    s = s.replace(/`([^`]+?)`/g, "<code>$1</code>");
    return s;
  }

  // is this paragraph an authorial aside, not record content?
  function metaPara(t) {
    const s = t.trim();
    if (/^\*\(.*\)\*$/.test(s)) return true;                 // *(authorial aside)*
    if (/^\*?to develop/i.test(s)) return true;
    if (/^\*?\(/.test(s) && /keep the mystery|to develop|to reconcile|register \/|draft|\bcf\.|this note/i.test(s)) return true;
    return false;
  }
  function metaQuote(t) {
    return /authorial note|keep the mystery|this note|metaphysics live/i.test(t);
  }

  // render a block of source lines to HTML, dropping meta + structural cruft
  function renderBlocks(lines) {
    const html = [];
    let para = [], quote = [], inList = false;

    function flushPara() {
      if (!para.length) return;
      const text = para.join(" "); para = [];
      if (metaPara(text)) return;
      html.push("<p>" + inline(text) + "</p>");
    }
    function flushQuote() {
      if (!quote.length) return;
      const text = quote.join(" "); quote = [];
      if (metaQuote(text)) return;
      html.push("<blockquote>" + inline(text) + "</blockquote>");
    }
    function closeList() { if (inList) { html.push("</ul>"); inList = false; } }

    for (let i = 0; i < lines.length; i++) {
      const t = lines[i].trim();
      if (t === "") { flushPara(); flushQuote(); closeList(); continue; }
      if (/^Project:\s/i.test(t)) continue;
      if (/^(-{3,}|\*{3,})$/.test(t)) { flushPara(); flushQuote(); closeList(); continue; } // drop hr
      const h = t.match(/^(#{3,6})\s+(.*)$/);                 // sub-heading (### within a section)
      if (h) { flushPara(); flushQuote(); closeList(); html.push("<h3>" + inline(h[2]) + "</h3>"); continue; }
      if (/^>\s?/.test(t)) { flushPara(); closeList(); quote.push(t.replace(/^>\s?/, "")); continue; }
      const li = t.match(/^[-*]\s+(.*)$/);
      if (li) { flushPara(); flushQuote(); if (!inList) { html.push("<ul>"); inList = true; } html.push("<li>" + inline(li[1]) + "</li>"); continue; }
      flushQuote(); closeList(); para.push(t);
    }
    flushPara(); flushQuote(); closeList();
    return html.join("\n");
  }

  function plainLen(lines) {
    return lines.join(" ").replace(/[#>*`\[\]|]/g, "").replace(/\s+/g, " ").trim().length;
  }

  function labelFor(normTitle, rawTitle) {
    if (HEADING_LABELS[normTitle]) return HEADING_LABELS[normTitle];
    return rawTitle.replace(/\*/g, "")
      .replace(/\[\[([^\]|]+)(\|[^\]]+)?\]\]/g, "$1")
      .replace(/#/g, "").trim().toUpperCase();
  }

  // ====================================================================
  //  Split a record into institutional sections
  // ====================================================================
  function splitSections(entry) {
    const lines = entry.raw.replace(/\r\n/g, "\n").split("\n");
    const sections = [];          // {norm,label,lines}
    let pre = [];
    let cur = null;
    for (let i = 0; i < lines.length; i++) {
      const m = lines[i].match(/^(#{1,2})\s+(.*)$/);
      if (m) {
        const nt = norm(m[2]);
        // a level-1 heading equal to the record title is just the title
        if (m[1].length === 1 && nt === entry.key) { cur = null; continue; }
        if (cur) sections.push(cur); else { /* preamble already captured below */ }
        cur = { norm: nt, label: labelFor(nt, m[2]), lines: [] };
      } else {
        if (cur) cur.lines.push(lines[i]); else pre.push(lines[i]);
      }
    }
    if (cur) sections.push(cur);
    return { pre: pre, sections: sections };
  }

  // ====================================================================
  //  Build the page list for an entry
  // ====================================================================
  function buildPages(entry) {
    const d = DOSSIERS[entry.key];
    const pages = [];

    // page 1: institutional header
    pages.push({ label: "FILE HEADER", html: dossierHTML(entry, d) });
    const mediaPage = mediaHTML(entry, d);
    if (mediaPage) pages.push({ label: "MEDIA ARCHIVE", html: mediaPage });

    // curated records (characters, Eirskel): use authored sections, not .md body
    if (d && d.sections) {
      d.sections.forEach(function (s) {
        const body = renderBlocks(s.md.split("\n"));
        if (body.trim()) pages.push({ label: s.label, html: body });
      });
      return pages;
    }

    const compact = entry.raw.replace(/^#.*$/m, "").replace(/\[\[|\]\]|\*/g, "").trim();
    const stub = entry.empty || compact.length < 70;
    if (stub) return pages;

    const parsed = splitSections(entry);

    if (isPerson(entry)) {
      parsed.sections.forEach(function (s) {
        if (!PERSON_KEEP[s.norm]) return;
        const body = renderBlocks(s.lines);
        if (body.trim()) pages.push({ label: s.label, html: body });
      });
      return pages;
    }

    // places: preamble becomes a SUMMARY page only if substantial after cleaning
    const preBody = renderBlocks(parsed.pre);
    if (preBody.replace(/<[^>]+>/g, "").trim().length > 200) {
      pages.push({ label: "SUMMARY", html: preBody });
    }
    parsed.sections.forEach(function (s) {
      if (skipSectionGlobal(s.norm)) return;
      const body = renderBlocks(s.lines);
      if (body.trim()) pages.push({ label: s.label, html: body });
    });
    return pages;
  }

  function dossierHTML(entry, d) {
    const m = entry.meta;
    if (!d) {
      d = { title: m.code + " // " + entry.title.toUpperCase(), sub: "", fields: [], relevance: "", abstract: "" };
    }
    let h = '<div class="doss">';
    const primary = d.media && d.media.idPhoto;
    if (primary) h += '<div class="doss-head has-media"><div class="doss-copy">';
    h += '<div class="doss-title">' + escapeHtml(d.title) + "</div>";
    if (d.sub) h += '<div class="doss-sub">' + inline(d.sub) + "</div>";
    if (primary) {
      h += '</div><figure class="id-photo evidence-frame' + (entry.group === "BIOLOGICALS" ? " creature-photo" : "") + '">' +
        '<img src="' + escapeAttr(primary.src) + '" alt="">' +
        '<figcaption>' + escapeHtml(primary.caption || "IDENTIFICATION IMAGE") + "</figcaption></figure></div>";
    }
    if (d.fields && d.fields.length) {
      h += '<table class="doss-fields">';
      d.fields.forEach(function (f) {
        h += "<tr><td class='k'>" + escapeHtml(f[0]) + "</td><td>" + inline(f[1]) + "</td></tr>";
      });
      h += "</table>";
    }
    if (d.relevance) {
      h += '<div class="doss-rel"><span class="lbl">RELEVANCE</span>' + inline(d.relevance) + "</div>";
    }
    if (d.abstract) {
      h += '<div class="doss-abstract"><span class="doss-h">ABSTRACT</span><p>' + inline(d.abstract) + "</p></div>";
    }
    h += "</div>";
    return h;
  }

  function escapeAttr(s) {
    return escapeHtml(s || "").replace(/`/g, "&#96;");
  }

  function mediaHTML(entry, d) {
    const media = d && d.media;
    if (!media) return "";
    const images = (media.images || []).slice();
    const audio = (media.audio || []).slice();
    if (!images.length && !audio.length) return "";
    let h = '<div class="media-archive">';
    h += '<h2>ATTACHED EVIDENCE // ' + escapeHtml(entry.meta.code) + "</h2>";
    if (images.length) {
      h += '<div class="media-label">IMAGE GALLERY</div><div class="terminal-gallery">';
      images.forEach(function (img, i) {
        h += '<figure class="evidence-frame gallery-frame">' +
          '<img src="' + escapeAttr(img.src) + '" alt="">' +
          '<figcaption><span>IMG-' + String(i + 1).padStart(2, "0") + "</span> " +
          escapeHtml(img.caption || img.name || "unlabelled evidence") + "</figcaption></figure>";
      });
      h += "</div>";
    }
    if (audio.length) {
      h += '<div class="media-label">AUDIO ARCHIVE</div><div class="terminal-audio-list">';
      audio.forEach(function (clip, i) {
        h += '<div class="audio-evidence cassette-deck">' +
          '<div class="audio-code">AUD-' + String(i + 1).padStart(2, "0") + "</div>" +
          '<div class="audio-title">' + escapeHtml(clip.title || clip.name || "unlabelled audio") + "</div>" +
          '<div class="eq-visual" aria-hidden="true">' +
            '<span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>' +
          '</div>' +
          '<button class="audio-play" data-audio-action="toggle" type="button">PLAY</button>' +
          '<input class="audio-seek" data-audio-action="seek" type="range" min="0" max="1000" value="0">' +
          '<div class="audio-time">00:00 / 00:00</div>' +
          '<audio preload="metadata" src="' + escapeAttr(clip.src) + '"></audio>' +
          "</div>";
      });
      h += "</div>";
    }
    return h + "</div>";
  }

  // ====================================================================
  //  Screen output: clear / print / cascade reveal
  // ====================================================================
  function scrollTop() { out.scrollTop = 0; }
  function scrollBottom() { out.scrollTop = out.scrollHeight; }

  let revealTimer = null, revealing = false, skipFn = null;
  function cancelReveal() {
    if (revealTimer) { clearTimeout(revealTimer); revealTimer = null; }
    if (revealing && skipFn) skipFn();
    revealing = false; skipFn = null;
  }
  function clearScreen() { cancelReveal(); out.innerHTML = ""; }

  function printHTML(html) {
    const d = document.createElement("div");
    d.innerHTML = html; out.appendChild(d); return d;
  }
  function revealHTML(html, delay, toBottom) {
    delay = delay || 30;
    const wrap = document.createElement("div"); wrap.innerHTML = html;
    const kids = Array.from(wrap.childNodes);
    const host = document.createElement("div"); out.appendChild(host);
    let i = 0; revealing = true;
    skipFn = function () { while (i < kids.length) { host.appendChild(kids[i]); i++; } if (toBottom) scrollBottom(); };
    (function step() {
      if (i >= kids.length) { revealing = false; revealTimer = null; return; }
      host.appendChild(kids[i]); i++;
      if (toBottom) scrollBottom();
      revealTimer = setTimeout(step, delay);
    })();
  }

  function sleep(ms) { return new Promise(function (r) { setTimeout(r, ms); }); }
  let bootSkip = false;
  async function typeLine(text, cls, cps) {
    const span = document.createElement("div"); if (cls) span.className = cls;
    out.appendChild(span);
    if (bootSkip) { span.innerHTML = text; scrollBottom(); return; }
    const speed = 1000 / (cps || 90);
    for (let i = 0; i < text.length; i++) {
      span.innerHTML = text.slice(0, i + 1); scrollBottom();
      if (bootSkip) { span.innerHTML = text; break; }
      await sleep(speed);
    }
  }

  // ====================================================================
  //  Views
  // ====================================================================
  function statusStamp(m) {
    return '<span class="stamp idx-stat ' + (m.tone || "dim") + '">' + m.status + "</span>";
  }

  // index display order, and persons nested under a parent record
  const DISPLAY_ORDER = (CONTENT.displayOrder || []).slice();
  const AFFIL = Object.assign({}, CONTENT.affiliations || {});
  const COLLAPSED_GROUPS = {};
  const AFFIL_PARENT = {};
  Object.keys(AFFIL).forEach(function (p) { AFFIL[p].forEach(function (k) { AFFIL_PARENT[k] = p; }); });

  function rowHTML(e, sub) {
    return '<div class="idx-row' + (sub ? " idx-sub" : "") + '" data-target="' + e.key + '">' +
      (sub ? '<span class="idx-arrow">↳</span>' : "") +
      '<span class="idx-code">' + e.meta.code + "</span>" +
      '<span class="idx-name">' + escapeHtml(e.title) + "</span></div>";
  }

  function showIndex() {
    clearScreen();
    const ordered = DISPLAY_ORDER.map(function (k) { return byKey[k]; }).filter(Boolean);
    DATA.forEach(function (e) { if (DISPLAY_ORDER.indexOf(e.key) === -1) ordered.push(e); });

    const groups = {}, order = [];
    ordered.forEach(function (e) {
      if (AFFIL_PARENT[e.key]) return;                 // affiliates render nested, not as group rows
      if (!groups[e.group]) { groups[e.group] = []; order.push(e.group); }
      groups[e.group].push(e);
    });

    let h = '<div class="banner-sm">BOUNDARY RESEARCH INSTITUTE — ARCHIVE INDEX</div>';
    h += '<p class="dim">' + DATA.length + " records on file. " +
         'Click a row to open a file. Select <span class="hot">MAP</span> for the survey chart.</p>';
    h += '<div class="idx-row" data-action="map"><span class="idx-code">MAP</span>' +
         '<span class="idx-name">Survey Chart — De Râne</span></div>';
    order.forEach(function (g) {
      const gkey = norm(g);
      const collapsed = !!COLLAPSED_GROUPS[gkey];
      h += '<div class="idx-group idx-toggle' + (collapsed ? " collapsed" : "") + '" data-action="group:' + gkey + '">' +
        '<span class="idx-caret">' + (collapsed ? "+" : "-") + "</span> — " + escapeHtml(g) + " —</div>";
      h += '<div class="idx-group-body' + (collapsed ? " collapsed" : "") + '">';
      if (CATEGORY_NOTES[g]) {
        h += '<div class="idx-note"><span>' + escapeHtml(CATEGORY_NOTES[g].title || g) +
          "</span>" + inline(CATEGORY_NOTES[g].body || "") + "</div>";
      }
      groups[g].forEach(function (e) {
        h += rowHTML(e, false);
        if (AFFIL[e.key]) {
          AFFIL[e.key].forEach(function (k) { if (byKey[k]) h += rowHTML(byKey[k], true); });
        }
      });
      h += "</div>";
    });
    const followIndexReveal = !window.matchMedia(
      "(max-width: 780px), (pointer: coarse)"
    ).matches;
    revealHTML(h, 28, followIndexReveal);
    if (!followIndexReveal) out.scrollTop = 0;
  }

  // survey chart ------------------------------------------------------
  // coordinates in a 400x240 viewBox, traced from the reference map
  const MAP_DOTS = [
    { key: "vaarden",  label: "VAARDEN",   x: 248, y: 112 },
    { key: "breisk",   label: "BREISK",    x: 136, y: 132 },
    { key: "station9", label: "STATION 9", x: 126, y: 84 },
    { key: "eirskel",  label: "EIRSKEL",   x: 205, y: 152 },
  ];
  const MAP_COAST =
    "M148,154 L140,142 L130,126 L132,106 L126,92 L138,76 L140,60 " +
    "L158,52 L170,40 L194,44 L212,34 L238,42 L256,38 L276,52 " +
    "L292,68 L290,88 L306,104 L296,124 L302,140 L288,154 Z";

  function chartDefs() {
    return '<defs>' +
      '<pattern id="landDots" width="6" height="6" patternUnits="userSpaceOnUse">' +
        '<circle cx="1.5" cy="1.5" r=".72" class="land-dot"/>' +
      '</pattern>' +
      '</defs>';
  }

  function chartGrid() {
    let s = '<rect class="chart-sea" x="8" y="8" width="384" height="224"/>';
    s += '<rect class="chart-frame" x="8" y="8" width="384" height="224"/>';
    for (let x = 50; x < 400; x += 50) s += '<line class="gridline" x1="' + x + '" y1="8" x2="' + x + '" y2="232"/>';
    for (let y = 40; y < 240; y += 40) s += '<line class="gridline" x1="8" y1="' + y + '" x2="392" y2="' + y + '"/>';
    s += '<text class="mfeat" x="14" y="20">BRI SURVEY GRID</text>';
    s += '<path class="scale" d="M302,220 H362"/><path class="scale-tick" d="M302,216 V224 M332,216 V224 M362,216 V224"/>';
    s += '<text class="mfeat" x="332" y="216" text-anchor="middle">0 / 30 / 60 km</text>';
    s += '<path class="scale" d="M366,34 L366,14 L360,24 M366,14 L372,24"/>';
    s += '<text class="mfeat" x="374" y="28">N</text>';
    return s;
  }

  function buildMapSVG() {
    let s = '<svg viewBox="0 0 400 240" preserveAspectRatio="xMidYMid meet">';
    s += chartDefs();
    s += chartGrid();
    // political outline, fixed perimeter, and Institute effect-zone boundaries
    s += '<path class="mainland" d="M94,232 L94,178 L148,154 L288,154 L344,178 L344,232 Z"/>';
    s += '<path class="coast" d="' + MAP_COAST + '"/>';
    s += '<path class="land-dots-fill" d="' + MAP_COAST + '"/>';
    s += '<path class="perimeter" d="' + MAP_COAST + '"/>';
    s += '<path class="polity-border" d="M176,46 L174,82 L162,112 L166,154"/>';
    s += '<path class="polity-border" d="M226,38 L230,78 L246,110 L238,154"/>';
    s += '<path class="polity-border" d="M132,106 L184,104 L228,94 L302,104"/>';
    s += '<path class="zone" d="M154,56 L214,42 L276,58 L292,86 L286,118 L260,144 L214,150 L174,140 L144,112 L146,78 Z"/>';
    s += '<path class="zone" d="M176,64 L218,52 L260,66 L276,88 L270,114 L246,136 L208,140 L180,128 L162,104 L164,80 Z"/>';
    s += '<path class="zone deep" d="M194,70 L224,62 L250,74 L260,94 L250,114 L224,126 L198,120 L184,102 L184,82 Z"/>';
    s += '<path class="route" d="M136,132 Q164,124 192,130 Q224,136 248,112"/>';
    s += '<circle class="pool" cx="215" cy="74" r="6"/>';
    // cordon across the neck
    s += '<line class="cordon" x1="150" y1="152" x2="300" y2="152"/>';
    s += '<text class="mfeat" x="304" y="154">CORDON</text>';
    // labels
    s += '<text class="mfeat" x="34" y="30">THE BOUNDARY — FIXED PERIMETER</text>';
    s += '<text class="mfeat" x="40" y="128" letter-spacing="2">SEA</text>';
    s += '<text class="mfeat" x="282" y="126">MID-BAND LIMIT</text>';
    s += '<text class="mfeat" x="124" y="192">EXTERIOR / MAINLAND</text>';
    s += '<text class="mfeat" x="88" y="145">BREISK-VAARDEN TRACK</text>';
    // deep / survey void (clickable -> The Boundary)
    s += '<g class="mapdot void" data-target="theboundary">' +
         '<path class="voidzone" d="M170,62 L214,50 L258,64 L276,88 L264,116 L230,132 L194,124 L166,102 Z"/>' +
         '<text class="mlabel vlabel" x="215" y="44" text-anchor="middle">DEEP / SURVEY VOID</text>' +
         "</g>";
    // location markers
    MAP_DOTS.forEach(function (d) {
      s += '<g class="mapdot" data-target="' + d.key + '">' +
           '<circle class="halo" cx="' + d.x + '" cy="' + d.y + '" r="3.2"/>' +
           '<circle class="core" cx="' + d.x + '" cy="' + d.y + '" r="2.4"/>' +
           '<text class="mlabel" x="' + (d.x + 7) + '" y="' + (d.y + 2.5) + '">' + d.label + "</text>" +
           "</g>";
    });
    // anomalous sites — provisional, relocate after each NCE
    [{ key: "silenthollow", label: "Σ-2", x: 188, y: 62 },
     { key: "thelosthour", label: "Τ-1", x: 238, y: 60 },
     { key: "theunchanginglight", label: "Λ-1", x: 203, y: 112 }].forEach(function (a) {
      s += '<g class="mapdot anom" data-target="' + a.key + '">' +
           '<circle class="halo" cx="' + a.x + '" cy="' + a.y + '" r="2.6"/>' +
           '<circle class="core" cx="' + a.x + '" cy="' + a.y + '" r="1.8"/>' +
           '<text class="mlabel anomlabel" x="' + (a.x + 6) + '" y="' + (a.y + 2) + '">' + a.label + "</text></g>";
    });
    s += '<text class="mfeat" x="200" y="233" text-anchor="middle">anomalous sites (amber) — positions provisional, reset each NCE</text>';
    s += "</svg>";
    return s;
  }

  function dotSVG(d) {
    const anchor = d.anchor || "start";
    const dx = anchor === "end" ? -7 : 7;
    return '<g class="mapdot" data-target="' + d.key + '">' +
      '<circle class="halo" cx="' + d.x + '" cy="' + d.y + '" r="3.2"/>' +
      '<circle class="core" cx="' + d.x + '" cy="' + d.y + '" r="2.4"/>' +
      '<text class="mlabel" x="' + (d.x + dx) + '" y="' + (d.y + 2.5) + '" text-anchor="' + anchor + '">' + d.label + "</text></g>";
  }

  // Virelsk (country): peninsula rising off the mainland coast, Kalliros across the sea
  const VIRELSK_COAST =
    "M72,188 L94,160 L126,150 L172,150 L156,126 L150,96 " +
    "L164,70 L198,50 L236,58 L266,82 L280,114 L252,150 " +
    "L300,156 L330,180 L300,204 L252,218 L204,204 L154,220 " +
    "L112,204 Z";
  const KALLIROS_COAST =
    "M320,28 L346,18 L376,24 L386,44 L372,62 L340,60 L314,46 Z";
  const VIRELSK_DOTS = [
    { key: "dreiskel", label: "DREISKEL", x: 138, y: 180 },
    { key: "eirskel",  label: "EIRSKEL",    x: 208, y: 150 },
    { key: "kalliros", label: "KALLIROS", x: 342, y: 39  },
  ];
  function buildVirelskSVG() {
    let s = '<svg viewBox="0 0 400 240" preserveAspectRatio="xMidYMid meet">';
    s += chartDefs();
    s += chartGrid();
    s += '<path class="coast" d="' + VIRELSK_COAST + '"/>';
    s += '<path class="land-dots-fill" d="' + VIRELSK_COAST + '"/>';
    s += '<path class="coast" d="' + KALLIROS_COAST + '"/>';
    s += '<path class="land-dots-fill" d="' + KALLIROS_COAST + '"/>';
    s += '<path class="polity-border" d="M172,150 L190,116 L198,50"/>';
    s += '<path class="polity-border" d="M252,150 L236,116 L236,58"/>';
    s += '<path class="polity-border" d="M94,160 L152,176 L204,204"/>';
    s += '<path class="polity-border" d="M252,218 L238,180 L252,150 L300,156"/>';
    s += '<path class="polity-border" d="M314,46 L346,42 L386,44"/>';
    s += '<path class="seal" d="M156,126 L150,96 L164,70 L198,50 L236,58 L266,82 L280,114 L252,150 L208,150 L176,138 Z"/>';
    s += '<path class="route" d="M100,174 Q154,160 208,150"/>';
    s += '<path class="route" d="M252,150 Q304,118 360,58"/>';
    s += '<line class="cordon" x1="172" y1="150" x2="252" y2="150"/>';
    s += '<text class="mfeat" x="256" y="152">CORDON</text>';
    s += '<text class="mfeat" x="270" y="126">Q-PERIMETER</text>';
    s += '<text class="mfeat" x="300" y="104">SEA ACCESS / BRI</text>';
    s += '<text class="mfeat" x="118" y="170" letter-spacing="2">CAPITAL DISTRICT</text>';
    s += '<text class="mfeat" x="110" y="190" font-size="9" letter-spacing="3">VIRELSK</text>';
    s += '<text class="mfeat" x="52" y="70" letter-spacing="2">SEA</text>';
    s += '<text class="mfeat" x="112" y="132" letter-spacing="2">WESTERN BAY</text>';
    s += '<text class="mfeat" x="282" y="138" letter-spacing="2">EASTERN BAY</text>';
    s += '<g class="mapdot void" data-target="theboundary">' +
         '<path class="voidzone" d="M168,78 L204,60 L240,70 L260,96 L246,122 L210,136 L180,124 L160,100 Z"/>' +
         '<text class="mlabel vlabel" x="210" y="40" text-anchor="middle">DE RÂNE / THE BOUNDARY</text>' +
         "</g>";
    VIRELSK_DOTS.forEach(function (d) { s += dotSVG(d); });
    s += "</svg>";
    return s;
  }

  const MAP_LEGEND = {
    derane:  ["theboundary", "vaarden", "breisk", "station9", "eirskel", "silenthollow", "thelosthour", "theunchanginglight"],
    virelsk: ["virelsk", "dreiskel", "theboundary", "eirskel", "kalliros"],
  };
  function mapLegend(which) {
    let leg = '<div class="maplegend">';
    (MAP_LEGEND[which] || []).forEach(function (k) {
      const e = byKey[k]; if (!e) return;
      leg += '<span class="maplegend-item" data-target="' + k + '">' +
             '<span class="ml-code">' + e.meta.code + "</span> " + escapeHtml(e.title) + "</span>";
    });
    return leg + "</div>";
  }
  function mapNav(active) {
    function b(id, label) {
      return '<button data-action="map:' + id + '" class="ebtn' + (id === active ? " on" : "") + '">' + label + "</button>";
    }
    return '<div class="eb-nav">' + b("derane", "DE RÂNE") + b("virelsk", "VIRELSK") +
      '<span class="eb-pos">click a marker to open its file</span>' +
      '<button data-action="index" class="ebtn">INDEX</button></div>';
  }
  function showMap(which) {
    which = (which === "virelsk") ? "virelsk" : "derane";
    clearScreen();
    const title = which === "virelsk"
      ? "SURVEY CHART · VIRELSK · host territory"
      : "SURVEY CHART · DE RÂNE · CTA-LINK";
    printHTML('<div class="entry-bar"><div class="eb-id">' + title + "</div>" + mapNav(which) + "</div>");
    printHTML('<div class="mapwrap">' + (which === "virelsk" ? buildVirelskSVG() : buildMapSVG()) + "</div>");
    printHTML(mapLegend(which));
    scrollTop();
  }

  // paged entry viewer ------------------------------------------------
  let cur = null;   // { entry, pages, i }

  function openEntry(key) {
    const e = byKey[key];
    if (!e) { printHTML('<div class="alert">&gt; no record matches that reference.</div>'); return; }
    cur = { entry: e, pages: buildPages(e), i: 0 };
    renderPage();
  }

  function renderPage() {
    clearScreen();
    const e = cur.entry, m = e.meta, n = cur.pages.length, i = cur.i;
    const page = cur.pages[i];

    let bar = '<div class="entry-bar">';
    bar += '<div class="eb-id">' + m.code + " · " + escapeHtml(e.title.toUpperCase()) + "</div>";
    bar += '<div class="eb-nav entry-sections">';
    cur.pages.forEach(function (p, idx) {
      bar += '<button data-action="page:' + idx + '" class="ebtn' + (idx === i ? " on" : "") + '">' +
        escapeHtml(p.label) + "</button>";
    });
    bar += '</div>' +
           '<div class="eb-pos">SECTION ' + (i + 1) + " / " + n + " — " + escapeHtml(page.label) + "</div></div>";
    printHTML(bar);
    scrollTop();
    revealHTML(page.html + '<div class="entry-return"><button data-action="index" class="ebtn">INDEX</button></div>', 18, false);
  }

  function pageStep(delta) {
    if (!cur) return;
    const ni = cur.i + delta;
    if (ni < 0 || ni >= cur.pages.length) return;
    cur.i = ni; renderPage();
  }

  function fmtTime(seconds) {
    if (!isFinite(seconds) || seconds < 0) seconds = 0;
    const m = Math.floor(seconds / 60);
    const s = Math.floor(seconds % 60);
    return String(m).padStart(2, "0") + ":" + String(s).padStart(2, "0");
  }

  function syncAudioDeck(deck) {
    const audio = deck.querySelector("audio");
    const seek = deck.querySelector(".audio-seek");
    const time = deck.querySelector(".audio-time");
    const play = deck.querySelector(".audio-play");
    if (!audio || !seek || !time || !play) return;
    const duration = audio.duration || 0;
    seek.value = duration ? Math.round((audio.currentTime / duration) * 1000) : 0;
    time.textContent = fmtTime(audio.currentTime) + " / " + fmtTime(duration);
    play.textContent = audio.paused ? "PLAY" : "PAUSE";
    deck.classList.toggle("playing", !audio.paused);
  }

  function stopOtherDecks(activeAudio) {
    out.querySelectorAll(".cassette-deck audio").forEach(function (audio) {
      if (audio !== activeAudio) audio.pause();
    });
  }

  // search ------------------------------------------------------------
  function doSearch(term) {
    clearScreen();
    const q = term.trim().toLowerCase();
    let h = '<div class="echo">archive&gt; search ' + escapeHtml(term) + "</div>";
    if (!q) { printHTML(h + '<div class="dim">usage: search &lt;term&gt;</div>'); return; }
    const esc = q.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    let total = 0;
    DATA.forEach(function (e) {
      if (e.empty) return;
      const lc = e.raw.toLowerCase();
      const hits = (lc.match(new RegExp(esc, "g")) || []).length;
      if (!hits) return;
      total += hits;
      let idx = lc.indexOf(q);
      const start = Math.max(0, idx - 38), end = Math.min(e.raw.length, idx + q.length + 44);
      let snip = escapeHtml(e.raw.slice(start, end).replace(/\s+/g, " ").trim())
        .replace(new RegExp("(" + esc + ")", "ig"), '<span class="hot">$1</span>');
      h += '<div class="idx-row" data-target="' + e.key + '" style="display:block">' +
             '<span class="idx-code">' + e.meta.code + "</span> " +
             '<span class="idx-name">' + escapeHtml(e.title) + "</span> " +
             '<span class="dim">(' + hits + ')</span>' +
             '<div class="dim" style="padding-left:5.5em">…' + snip + "…</div></div>";
    });
    if (!total) h += '<div class="dim">no matches.</div>';
    revealHTML(h, 25, true);
  }

  function showHelp() {
    clearScreen();
    const h = "<h2>OPERATOR GUIDE</h2><ul>" +
      "<li>Click any index row to open a record.</li>" +
      "<li>Use the section buttons at the top of a file to jump between pages.</li>" +
      "<li>Use the <span class='hot'>INDEX</span> button at the bottom of a file to return to the record list.</li>" +
      "<li>Click cross-references, map markers, and media entries where available.</li>" +
      "</ul><p class='dim'>Press <span class='hot'>Esc</span> or click to skip text reveal.</p>";
    revealHTML(h, 22, true);
  }
  function showAbout() {
    clearScreen();
    const h = "<h2>ARCHIVE NOTICE</h2>" +
      "<blockquote>Contents are property of the Boundary Research Institute. " +
      "Records describe the phenomenon designated <em>De Râne</em>. " +
      "Cross-references marked <span class='xref-dead'>thus</span> have no file on this node. " +
      "Some records are incomplete by design — a place with no centre authors no record of itself.</blockquote>" +
      "<p class='dim'>This terminal reads the project's World notes and character files. " +
      "Headers are Institute-authored; record bodies are drawn from the source notes with authorial " +
      "annotations suppressed. Edit the .md files, run <span class='hot'>build.py</span>, refresh.</p>";
    revealHTML(h, 22, true);
  }

  // ====================================================================
  //  Command handling
  // ====================================================================
  const history = []; let hpos = -1;

  function resolve(arg) {
    arg = (arg || "").trim(); if (!arg) return null;
    if (byNumber[arg]) return byNumber[arg].key;
    const n = norm(arg);
    if (byKey[n]) return n;
    let hit = DATA.find(function (e) { return norm(e.meta.code) === n; });
    if (hit) return hit.key;
    hit = DATA.find(function (e) { return e.key.indexOf(n) === 0; }) ||
          DATA.find(function (e) { return e.key.indexOf(n) !== -1; });
    return hit ? hit.key : null;
  }

  function run(raw) {
    const line = raw.trim(); if (!line) return;
    history.push(line); hpos = history.length;
    const sp = line.indexOf(" ");
    const verb = (sp === -1 ? line : line.slice(0, sp)).toLowerCase();
    const arg = sp === -1 ? "" : line.slice(sp + 1);

    switch (verb) {
      case "help": case "?": showHelp(); break;
      case "about": case "notice": showAbout(); break;
      case "index": case "list": case "ls": case "home": case "menu": case "back":
        cur = null; showIndex(); break;
      case "open": case "view": case "read": case "cat": case "access": {
        const k = resolve(arg);
        if (k) openEntry(k);
        else { clearScreen(); printHTML('<div class="alert">&gt; no record: "' + escapeHtml(arg) + '". Try <span class="hot">index</span>.</div>'); }
        break;
      }
      case "next": case "n": case "fwd": pageStep(1); break;
      case "prev": case "p": case "back1": pageStep(-1); break;
      case "map": case "chart": case "survey": showMap(norm(arg)); break;
      case "search": case "grep": case "find": doSearch(arg); break;
      case "clear": case "cls": clearScreen(); break;
      case "whoami": clearScreen(); printHTML('<div class="dim">operator // clearance level 3</div>'); break;
      case "exit": case "quit": case "logout":
        clearScreen(); printHTML('<div class="dim">&gt; this door does not close behind you.</div>'); break;
      default: {
        const k = resolve(line);
        if (k) openEntry(k);
        else { clearScreen(); printHTML('<div class="alert">&gt; unknown command: "' + escapeHtml(verb) + '". Type <span class="hot">help</span>.</div>'); }
      }
    }
  }

  // ---------- input wiring ----------
  cmd.addEventListener("keydown", function (ev) {
    if (authKeyHandler) {
      if (ev.key === "Enter" || ev.key === "Backspace" || ev.key === "Escape") authKeyHandler(ev);
      return;
    }
    if (ev.key === "Enter") { const v = cmd.value; cmd.value = ""; run(v); }
    else if (ev.key === "ArrowUp") { if (history.length) { hpos = Math.max(0, hpos - 1); cmd.value = history[hpos] || ""; } ev.preventDefault(); }
    else if (ev.key === "ArrowDown") { if (history.length) { hpos = Math.min(history.length, hpos + 1); cmd.value = history[hpos] || ""; } ev.preventDefault(); }
    else if (ev.key === "Escape") { cancelReveal(); }
  });
  window.addEventListener("keydown", function (ev) {
    if (ev.ctrlKey && ev.shiftKey && (ev.key || "").toLowerCase() === "e") {
      ev.preventDefault();
      ev.stopPropagation();
      showArchiveEventAdmin();
      return;
    }
    if (ev.key === "Escape") cancelReveal();
  });

  out.addEventListener("click", function (ev) {
    const btn = ev.target.closest("[data-action]");
    if (btn) {
      if (btn.classList.contains("off")) return;
      const a = btn.getAttribute("data-action");
      if (a === "next") pageStep(1);
      else if (a === "prev") pageStep(-1);
      else if (a.indexOf("page:") === 0) {
        const idx = parseInt(a.split(":")[1], 10);
        if (!isNaN(idx) && cur && idx >= 0 && idx < cur.pages.length) { cur.i = idx; renderPage(); }
      }
      else if (a === "index") { cur = null; showIndex(); }
      else if (a.indexOf("map") === 0) { cur = null; showMap(a.indexOf(":") > -1 ? a.split(":")[1] : ""); }
      else if (a.indexOf("group:") === 0) {
        const gkey = a.split(":")[1];
        COLLAPSED_GROUPS[gkey] = !COLLAPSED_GROUPS[gkey];
        cur = null; showIndex();
      }
      return;
    }
    const audioControl = ev.target.closest("[data-audio-action]");
    if (audioControl) {
      const deck = audioControl.closest(".cassette-deck");
      const audio = deck && deck.querySelector("audio");
      if (!deck || !audio) return;
      const action = audioControl.getAttribute("data-audio-action");
      if (action === "toggle") {
        if (audio.paused) {
          stopOtherDecks(audio);
          audio.play().catch(function () {});
        } else audio.pause();
        syncAudioDeck(deck);
      }
      return;
    }
    const ref = ev.target.closest("[data-target]");
    if (ref) { openEntry(ref.getAttribute("data-target")); return; }
    if (revealing) cancelReveal();
  });

  out.addEventListener("input", function (ev) {
    const seek = ev.target.closest('[data-audio-action="seek"]');
    if (!seek) return;
    const deck = seek.closest(".cassette-deck");
    const audio = deck && deck.querySelector("audio");
    if (!audio || !audio.duration) return;
    audio.currentTime = (Number(seek.value) / 1000) * audio.duration;
    syncAudioDeck(deck);
  });

  out.addEventListener("timeupdate", function (ev) {
    const audio = ev.target.closest && ev.target.closest(".cassette-deck audio");
    if (audio) syncAudioDeck(audio.closest(".cassette-deck"));
  }, true);

  out.addEventListener("loadedmetadata", function (ev) {
    const audio = ev.target.closest && ev.target.closest(".cassette-deck audio");
    if (audio) syncAudioDeck(audio.closest(".cassette-deck"));
  }, true);

  out.addEventListener("pause", function (ev) {
    const audio = ev.target.closest && ev.target.closest(".cassette-deck audio");
    if (audio) syncAudioDeck(audio.closest(".cassette-deck"));
  }, true);

  out.addEventListener("play", function (ev) {
    const audio = ev.target.closest && ev.target.closest(".cassette-deck audio");
    if (audio) syncAudioDeck(audio.closest(".cassette-deck"));
  }, true);

  // ---------- clock + hush flavor ----------
  function tick() {
    const d = new Date(), p = function (n) { return String(n).padStart(2, "0"); };
    clock.textContent = p(d.getHours()) + ":" + p(d.getMinutes()) + ":" + p(d.getSeconds());
  }
  setInterval(tick, 1000); tick();
  function hushCycle() {
    if (Math.random() < 0.12) {
      hush.textContent = "HUSH: thinning"; hush.className = "warn";
      setTimeout(function () { hush.textContent = "HUSH: nominal"; hush.className = ""; }, 4000 + Math.random() * 4000);
    }
    setTimeout(hushCycle, 18000 + Math.random() * 22000);
  }
  setTimeout(hushCycle, 20000);

  // ====================================================================
  //  Audio
  // ====================================================================
  const bootAudio = document.createElement("audio");
  const glitchAudio = document.createElement("audio");
  bootAudio.src = AUDIO_SRC.boot;
  glitchAudio.src = AUDIO_SRC.glitch;
  bootAudio.loop = true;
  glitchAudio.loop = true;
  bootAudio.preload = "auto";
  glitchAudio.preload = "auto";
  bootAudio.volume = 0.34;
  glitchAudio.volume = 0.72;
  bootAudio.setAttribute("aria-hidden", "true");
  glitchAudio.setAttribute("aria-hidden", "true");
  bootAudio.className = "hidden";
  glitchAudio.className = "hidden";
  screen.appendChild(bootAudio);
  screen.appendChild(glitchAudio);

  let bootAudioWanted = false;
  let glitchAudioWanted = false;
  let audioUnlocked = false;

  function tryPlay(audio) {
    const p = audio.play();
    if (p && typeof p.catch === "function") p.catch(function () {});
  }

  function startBootAudio() {
    bootAudioWanted = true;
    if (bootAudio.paused) {
      bootAudio.currentTime = 0;
      bootAudio.volume = 0.34;
    }
    tryPlay(bootAudio);
  }

  function fadeAudio(audio, ms, target, pauseWhenDone) {
    target = target == null ? 0 : target;
    const start = audio.volume;
    const steps = Math.max(1, Math.floor(ms / 40));
    let i = 0;
    const timer = setInterval(function () {
      i++;
      audio.volume = start + (target - start) * (i / steps);
      if (i >= steps) {
        clearInterval(timer);
        audio.volume = target;
        if (pauseWhenDone) {
          audio.pause();
          audio.currentTime = 0;
        }
      }
    }, 40);
  }

  function stopBootAudio() {
    bootAudioWanted = false;
    fadeAudio(bootAudio, 900, 0, true);
  }

  function startGlitchAudio() {
    glitchAudioWanted = true;
    glitchAudio.currentTime = 0;
    glitchAudio.volume = 0.72;
    tryPlay(glitchAudio);
  }

  function stopGlitchAudio() {
    glitchAudioWanted = false;
    fadeAudio(glitchAudio, 520, 0, true);
  }

  function unlockAudio() {
    if (audioUnlocked) return;
    audioUnlocked = true;
    if (bootAudioWanted) tryPlay(bootAudio);
    if (glitchAudioWanted) tryPlay(glitchAudio);
  }
  window.addEventListener("pointerdown", unlockAudio, { once: true, capture: true });
  window.addEventListener("keydown", unlockAudio, { once: true, capture: true });

  // ====================================================================
  //  Boot
  // ====================================================================
  async function ghostInterference() {
    if (bootSkip) return;
    startGlitchAudio();
    const ghost = document.createElement("div");
    ghost.className = "signal-ghost";
    ghost.innerHTML =
      '<div class="ghost-static"></div>' +
      '<div class="ghost-window">' +
        '<div class="ghost-picture"><img class="ghost-face" src="' + IME_SIGNAL_FRAMES[0] + '" alt="unidentified signal face"></div>' +
        '<div class="ghost-subtitle"><span class="ghost-prefix">&gt;</span> <span class="ghost-subline"></span><span class="ghost-caret">_</span></div>' +
      '</div>' +
      '<div class="ghost-tear"></div>';
    screen.appendChild(ghost);
    const sub = ghost.querySelector(".ghost-subline");
    const face = ghost.querySelector(".ghost-face");
    const text = "somewhere, someone is still listening, right?  •  CAN YOU HEAR ME?";
    const preload = IME_SIGNAL_FRAMES.map(function (src) {
      const img = new Image();
      img.src = src;
      return img;
    });
    let frameIndex = 0;
    const frameTimer = setInterval(function () {
      frameIndex = (frameIndex + 1) % IME_SIGNAL_FRAME_SEQUENCE.length;
      const next = IME_SIGNAL_FRAME_SEQUENCE[frameIndex];
      face.src = IME_SIGNAL_FRAMES[next] || IME_SIGNAL_FRAMES[0];
      ghost.classList.toggle("frame-pop", next !== 0);
    }, 520);
    await sleep(360);
    for (let i = 0; i < text.length; i++) {
      sub.textContent = text.slice(0, i + 1);
      if (i === 48) ghost.classList.add("urgent");
      await sleep(i > 51 ? 42 : 58);
    }
    await sleep(2200);
    clearInterval(frameTimer);
    face.src = IME_SIGNAL_FRAMES[1] || IME_SIGNAL_FRAMES[0];
    stopGlitchAudio();
    ghost.classList.add("collapse");
    await sleep(760);
    preload.length = 0;
    ghost.remove();
  }

  async function boot() {
    out.innerHTML = "";
    promptLine.classList.add("hidden");
    cmd.disabled = true;
    startBootAudio();
    const banner =
      "  +--------------------------------------------------+\n" +
      "  |   B O U N D A R Y   R E S E A R C H   I N S T.   |\n" +
      "  |   D E   R A N E   ::   A R C H I V E   N O D E   |\n" +
      "  +--------------------------------------------------+";
    printHTML('<div class="banner">' + banner + "</div>");
    // each line: [text, css class, pause-after-ms]
    const lines = [
      ["", "", 250],
      ["BRI archive subsystem // node DE-RANE-3", "sys", 420],
      ["BRI//SYS v1.12 · CTA-LINK · quantum index", "faint", 460],
      ["establishing secure link . . . . . . . . OK", "dim", 360],
      ["POST . . . . . . . . . . . . . . . . . . OK", "dim", 300],
      ["mounting /vol/zone . . . . . . . . . . . OK", "dim", 280],
      ["mounting /vol/persons  . . . . . . . . . OK", "dim", 280],
      ["decrypting archive index . . . . . . . . OK", "dim", 360],
      ["ERR-NL/OPEN-DOOR: nonlocal echo on closed channel", "warn", 620],
      ["calibrating chronological array . . . . . OK", "dim", 520],
      ["  NOTE: array returned result prior to query.", "faint", 700],
      ["scanning region for active swell . . . . none", "dim", 600],
      ["authenticating operator . . . . . . . . . OK", "dim", 360],
      ["clearance level 3 granted.", "sys", 650],
      ["", "", 250],
      ["WARNING: contents classified. handle per protocol.", "warn", 520],
      ["WARNING: prolonged access is itself a form of exposure.", "warn", 900],
      ["", "", 200],
    ];
    for (let idx = 0; idx < lines.length; idx++) {
      const [txt, cls, pause] = lines[idx];
      if (txt === "") out.appendChild(document.createElement("div"));
      else await typeLine(txt, cls, 38);          // slower keystrokes
      if (idx === 8 && !bootSkip) {
        await sleep(220);
        await ghostInterference();
      }
      if (bootSkip) break;
      await sleep(bootSkip ? 0 : (pause || 250));  // beat between lines
    }
    await sleep(bootSkip ? 0 : 700);
    gate();
  }

  // ---- confidentiality gate ----
  function showNotice() {
    let h = '<div class="notice">';
    h += '<div class="notice-h">— CONFIDENTIALITY NOTICE —</div>';
    h += '<p>The records beyond this point are property of the Boundary Research Institute, ' +
         'classified under <span class="warn">Omega</span> protocols. All access is logged.</p>';
    h += '<p>Disclosure of <em>De Râne</em> phenomena to any party beyond the cordon is an ' +
         'offence under the Containment Act.</p>';
    h += '<p>By proceeding you affirm Level 3 clearance and accept that prolonged access ' +
         'constitutes a form of exposure.</p>';
    h += '<div class="ack-choice">AFFIRM CLEARANCE? <span class="hot">[Y] AUTHORIZE</span> ' +
         '<span class="dim">/</span> <span class="warn">[N] TERMINATE</span></div>';
    h += "</div>";
    printHTML(h); scrollBottom();
  }
  function waitForAck() {
    return new Promise(function (resolve) {
      function onKey(ev) {
        const k = (ev.key || "").toLowerCase();
        if (k === "y" || k === "enter") { cleanup(); resolve(true); }
        else if (k === "n" || k === "escape") { cleanup(); resolve(false); }
        ev.preventDefault(); ev.stopPropagation();
      }
      function cleanup() {
        document.removeEventListener("keydown", onKey, true);
        setAuthKeyHandler(null);
      }
      document.addEventListener("keydown", onKey, true);
      setAuthKeyHandler(onKey, "ack>");
    });
  }
  function enterArchive() {
    promptLine.classList.add("hidden");
    cmd.disabled = true;
    showIndex();
    scheduleArchiveEvent();
  }
  function terminated() {
    clearScreen();
    printHTML('<div class="alert">CONNECTION TERMINATED.</div>' +
      '<div class="dim">No clearance affirmed. Press any key to reconnect.</div>');
    function once(ev) {
      ev.preventDefault(); ev.stopPropagation();
      document.removeEventListener("keydown", once, true);
      setAuthKeyHandler(null);
      gate();
    }
    document.addEventListener("keydown", once, { once: true, capture: true });
    setAuthKeyHandler(once, "reconnect>");
  }
  const PASSWORD = "NIHIL";
  const SKIP_PROTOCOL = "REGIO";
  function passwordPrompt() {
    return new Promise(function (resolve) {
      let buf = "";
      const line = document.createElement("div");
      line.className = "ack";
      out.appendChild(line);
      function render() { line.innerHTML = "ENTER ACCESS CODE: " + "•".repeat(buf.length); scrollBottom(); }
      render();
      function onKey(ev) {
        const k = ev.key;
        if (k === "Enter") { line.className = "dim"; cleanup(); resolve(buf.toUpperCase() === PASSWORD); }
        else if (k === "Backspace") { buf = buf.slice(0, -1); render(); }
        else if (k && k.length === 1) { buf += k; render(); }
        ev.preventDefault(); ev.stopPropagation();
      }
      function cleanup() {
        document.removeEventListener("keydown", onKey, true);
        setAuthKeyHandler(null);
      }
      document.addEventListener("keydown", onKey, true);
      setAuthKeyHandler(onKey, "code>");
    });
  }
  async function gate() {
    let authed = false, tries = 0;
    while (!authed) {
      authed = await passwordPrompt();
      if (authed) { printHTML('<div class="sys">ACCESS CODE ACCEPTED.</div>'); break; }
      tries++;
      printHTML('<div class="alert">ACCESS DENIED.</div>');
      if (tries >= 3) printHTML('<div class="faint">access is logged. unauthorised attempts are reported to the directorate.</div>');
    }
    await sleep(bootSkip ? 0 : 500);
    showNotice();
    await sleep(bootSkip ? 0 : 350);
    await typeLine("ACKNOWLEDGE AND PROCEED?  [Y / N]", "ack", 24);
    const ok = await waitForAck();
    stopBootAudio();
    if (ok) enterArchive(); else terminated();
  }

  function awaitEntry() {
    out.innerHTML = "";
    promptLine.classList.remove("hidden");
    cmd.disabled = false;
    let bypassBuffer = "";
    printHTML(
      '<div class="banner-sm">BRI ARCHIVE NODE // STANDBY</div>' +
      '<p class="dim">audio channel sealed pending operator presence.</p>' +
      '<p class="ack">PRESS ANY KEY OR CLICK TO INITIALIZE TERMINAL</p>'
    );
    function cleanupStandby() {
      window.removeEventListener("pointerdown", start, true);
      window.removeEventListener("keydown", bypass, true);
      setAuthKeyHandler(null);
    }
    function start(ev) {
      if (ev && ev.type === "pointerdown" && ev.pointerType && ev.pointerType !== "mouse") {
        ev.preventDefault();
        ev.stopPropagation();
        focusAuthInput();
        return;
      }
      if (ev && ev.type === "keydown") {
        const k = ev.key || "";
        if (k === "Tab" || k === "Shift" || k === "Meta" || k === "Alt" || k === "Control") return;
      }
      if (ev) { ev.preventDefault(); ev.stopPropagation(); }
      cleanupStandby();
      unlockAudio();
      boot();
    }
    function bypass(ev) {
      if (ev && ev.type === "keydown") {
        const k = ev.key || "";
        if (k === "Enter") {
          start(ev);
          return;
        }
        if (k === "Tab" || k === "Shift" || k === "Meta" || k === "Alt" || k === "Control") return;
        if (k.length === 1) {
          bypassBuffer += k.toUpperCase();
          if (SKIP_PROTOCOL.indexOf(bypassBuffer) === 0) {
            ev.preventDefault(); ev.stopPropagation();
            if (bypassBuffer === SKIP_PROTOCOL) {
              cleanupStandby();
              stopBootAudio();
              stopGlitchAudio();
              clearScreen();
              printHTML('<div class="sys">DIRECTORATE OVERRIDE ACCEPTED.</div>');
              enterArchive();
            }
            return;
          }
        }
      }
      start(ev);
    }
    window.addEventListener("pointerdown", start, true);
    window.addEventListener("keydown", bypass, true);
    setAuthKeyHandler(bypass, "init>");
  }

  if (!DATA.length) {
    printHTML('<div class="alert">No archive data found. Run <span class="hot">python3 build.py</span> first.</div>');
  } else { awaitEntry(); }
})();
